import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
    title: 'Koszyk - 4lop',
    description: 'Generated by create next app',
}

export default function LayoutConfiguratorPage({ children }: { children: React.ReactNode }) {
    return children
}
