import styles from "@/styles/Account.module.scss"
import React, { Suspense } from 'react'
import { ChevronRight } from 'lucide-react'
import { Metadata } from "next"
import AccountLayout from "@/components/account_layout"


export const metadata: Metadata = {
    title: '4lop - Twoje konto',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <div className={styles.container4lop}>
                <h4 className={styles.navigation_label}>Strona główna <ChevronRight size={18} style={{marginInline: 6}} /> Konto użytkownika</h4>
                <div className={styles.title}>
                    <h1>Konto użytkownika</h1>
                    <span className={styles.line} />
                </div>

                <div className={styles.account_container}>
                    <Suspense fallback={null}>
                        <AccountLayout />
                    </Suspense>
                    
                    {children}
                </div>
            </div>
        </>
    )
}
