import { currentRole } from '@/lib/auth';
import { UserRole } from '@prisma/client';
import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import React from 'react';
import DashboardSidebar from '@/components/dashboard_sidebar';
import { MainNav } from '@/components/main-nav';
import { DashboardNav } from '@/components/nav';

const mainNav = [
    {
        title: "Sklep",
        href: "/sklep",
    },
    {
        title: "Blog",
        href: "/blog",
    },
]

const sidebarNav = [
    {
        title: "Strona główna",
        href: "/dashboard",
        icon: "home" as "home",
    },
    {
        title: "Zamówienia",
        href: "/dashboard/orders",
        icon: "order" as "order",
    },
    {
        title: "Użytkownicy",
        href: "/dashboard/users",
        icon: "users" as "users",
    },
    {
        title: "Opcje dostawy",
        href: "/dashboard/shipments",
        icon: "truck" as "truck",
    },
    {
        title: "Produkty",
        href: "/dashboard/products",
        icon: "products" as "products",
        hrTop: true
    },
    {
        title: "Kategorie",
        href: "/dashboard/categories",
        icon: "products" as "products",
    },
    {
        title: "Warianty produktów",
        href: "/dashboard/groups",
        icon: "products" as "products",
    },
    {
        title: "Edycja strony",
        href: "/dashboard/editing",
        icon: "edit" as "edit",
        hrTop: true
    },
]

export const metadata: Metadata = {
    title: 'Dashboard - 4lop',
    description: 'Generated by create next app',
};

export default async function LayoutDashboardPage({
    children,
}: {
    children: React.ReactNode;
}) {
    const userRole = await currentRole();
    if (userRole !== UserRole.ADMIN) {
        return notFound();
    }

    return (
        <div className="flex min-h-screen flex-col space-y-6 bg-[#FBFBFB] z-40">
            {/* <DashboardSidebar /> */}
            <header className='sticky top-0 z-50 border-b bg-background'>
                <div className='container flex items-center justify-between h-16 py-2'>
                    <MainNav items={mainNav} />
                </div>
            </header>
            <div className="container grid flex-1 gap-[12px] md:grid-cols-[200px_1fr] !py-0.5 !ps-0.5 !pe-0.5">
                <aside className="hidden w-[200px] flex-col md:flex">
                    <DashboardNav items={sidebarNav} />
                </aside>
                <main className="flex w-full flex-1 flex-col overflow-hidden">
                    {children}
                </main>
            </div>
            {/* <SiteFooter className="border-t" /> */}
        </div>
    );
}
