import { currentRole } from '@/lib/auth'
import { UserRole } from '@prisma/client'
import { Metadata } from 'next'
import { notFound } from 'next/navigation'
import React, { Suspense } from 'react'
import styles from "@/styles/Account.module.scss"
import { ChevronRight } from 'lucide-react'
import DashboardSidebar from '@/components/dashboard_sidebar'

export const metadata: Metadata = {
    title: 'Dashboard - 4lop',
    description: 'Generated by create next app',
}

export default async function LayoutDashboardPage({ children }: { children: React.ReactNode }) {
    const userRole = await currentRole()
    if (userRole !== UserRole.ADMIN) {
        return notFound()
    }

    return (
        <div className={styles.container}>
            <h4 className={styles.navigation_label}>Strona główna <ChevronRight size={18} style={{marginInline: 6}} /> Panel administratora</h4>
            <div className={styles.title}>
                <h1>Panel administratora</h1>
                <span className={styles.line} />
            </div>

            <div className={styles.account_container}>
                <Suspense fallback={null}>
                    <DashboardSidebar />
                </Suspense>
                
                {children}
            </div>
        </div>
    )
}
